{"uuid": "7324f037-5ded-4e92-93bd-ff674ab7b001", "children": ["34f0e14b-7e2d-4e1d-be2d-5d26aedc5693"], "befores": [{"name": "getdata", "status": "broken", "statusDetails": {"message": "KeyError: 'token'\n", "trace": "  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/test/work/API_Testframe/TestCase/test_login.py\", line 28, in getdata\n    self.request = Send_Request.Request()\n  File \"/Users/test/work/API_Testframe/Common/Send_Request.py\", line 35, in __init__\n    self.get_session = self.session.get_session()\n  File \"/Users/test/work/API_Testframe/Common/Session.py\", line 42, in get_session\n    auth = \"JWT \" + response.json()[\"token\"]\n"}, "start": 1605685739973, "stop": 1605685741004}], "start": 1605685739973, "stop": 1605685741220}